# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: D:/s181703/s181703/s181703L04/ZL04_IP2_181703_src/Zybo-Z7-Master.xdc

# Block Designs: bd/ZL04_Blk_181703/ZL04_Blk_181703.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ZL04_Blk_181703 || ORIG_REF_NAME==ZL04_Blk_181703} -quiet] -quiet

# IP: bd/ZL04_Blk_181703/ip/ZL04_Blk_181703_processing_system7_0_0/ZL04_Blk_181703_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ZL04_Blk_181703_processing_system7_0_0 || ORIG_REF_NAME==ZL04_Blk_181703_processing_system7_0_0} -quiet] -quiet

# IP: bd/ZL04_Blk_181703/ip/ZL04_Blk_181703_led_btn_ip_0_0/ZL04_Blk_181703_led_btn_ip_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ZL04_Blk_181703_led_btn_ip_0_0 || ORIG_REF_NAME==ZL04_Blk_181703_led_btn_ip_0_0} -quiet] -quiet

# IP: bd/ZL04_Blk_181703/ip/ZL04_Blk_181703_ps7_0_axi_periph_0/ZL04_Blk_181703_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ZL04_Blk_181703_ps7_0_axi_periph_0 || ORIG_REF_NAME==ZL04_Blk_181703_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/ZL04_Blk_181703/ip/ZL04_Blk_181703_rst_ps7_0_50M_0/ZL04_Blk_181703_rst_ps7_0_50M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ZL04_Blk_181703_rst_ps7_0_50M_0 || ORIG_REF_NAME==ZL04_Blk_181703_rst_ps7_0_50M_0} -quiet] -quiet

# IP: bd/ZL04_Blk_181703/ip/ZL04_Blk_181703_auto_pc_0/ZL04_Blk_181703_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ZL04_Blk_181703_auto_pc_0 || ORIG_REF_NAME==ZL04_Blk_181703_auto_pc_0} -quiet] -quiet

# XDC: bd/ZL04_Blk_181703/ZL04_Blk_181703_ooc.xdc
