# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: D:/s181703/ZL03_IP1_181703_src/Zybo-Z7-Master.xdc

# Block Designs: bd/ZL03_181703/ZL03_181703.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ZL03_181703 || ORIG_REF_NAME==ZL03_181703} -quiet] -quiet

# IP: bd/ZL03_181703/ip/ZL03_181703_processing_system7_0_0/ZL03_181703_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ZL03_181703_processing_system7_0_0 || ORIG_REF_NAME==ZL03_181703_processing_system7_0_0} -quiet] -quiet

# IP: bd/ZL03_181703/ip/ZL03_181703_axi_gpio_0_0/ZL03_181703_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ZL03_181703_axi_gpio_0_0 || ORIG_REF_NAME==ZL03_181703_axi_gpio_0_0} -quiet] -quiet

# IP: bd/ZL03_181703/ip/ZL03_181703_ps7_0_axi_periph_0/ZL03_181703_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ZL03_181703_ps7_0_axi_periph_0 || ORIG_REF_NAME==ZL03_181703_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/ZL03_181703/ip/ZL03_181703_rst_ps7_0_50M_0/ZL03_181703_rst_ps7_0_50M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ZL03_181703_rst_ps7_0_50M_0 || ORIG_REF_NAME==ZL03_181703_rst_ps7_0_50M_0} -quiet] -quiet

# IP: bd/ZL03_181703/ip/ZL03_181703_xbar_0/ZL03_181703_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ZL03_181703_xbar_0 || ORIG_REF_NAME==ZL03_181703_xbar_0} -quiet] -quiet

# IP: bd/ZL03_181703/ip/ZL03_181703_led_ip_0_0/ZL03_181703_led_ip_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ZL03_181703_led_ip_0_0 || ORIG_REF_NAME==ZL03_181703_led_ip_0_0} -quiet] -quiet

# IP: bd/ZL03_181703/ip/ZL03_181703_auto_pc_0/ZL03_181703_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ZL03_181703_auto_pc_0 || ORIG_REF_NAME==ZL03_181703_auto_pc_0} -quiet] -quiet

# XDC: bd/ZL03_181703/ZL03_181703_ooc.xdc
