# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/s181703/ZL02_LED2_181703_prj/ZL02_LED2_181703_prj.srcs/sources_1/bd/ZL02_Blk_181703/ip/ZL02_Blk_181703_axi_gpio_0_0/ZL02_Blk_181703_axi_gpio_0_0.xci
# IP: The module: 'ZL02_Blk_181703_axi_gpio_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/s181703/ZL02_LED2_181703_prj/ZL02_LED2_181703_prj.srcs/sources_1/bd/ZL02_Blk_181703/ip/ZL02_Blk_181703_axi_gpio_0_0/ZL02_Blk_181703_axi_gpio_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'ZL02_Blk_181703_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/s181703/ZL02_LED2_181703_prj/ZL02_LED2_181703_prj.srcs/sources_1/bd/ZL02_Blk_181703/ip/ZL02_Blk_181703_axi_gpio_0_0/ZL02_Blk_181703_axi_gpio_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ZL02_Blk_181703_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/s181703/ZL02_LED2_181703_prj/ZL02_LED2_181703_prj.srcs/sources_1/bd/ZL02_Blk_181703/ip/ZL02_Blk_181703_axi_gpio_0_0/ZL02_Blk_181703_axi_gpio_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'ZL02_Blk_181703_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: d:/s181703/ZL02_LED2_181703_prj/ZL02_LED2_181703_prj.srcs/sources_1/bd/ZL02_Blk_181703/ip/ZL02_Blk_181703_axi_gpio_0_0/ZL02_Blk_181703_axi_gpio_0_0.xci
# IP: The module: 'ZL02_Blk_181703_axi_gpio_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/s181703/ZL02_LED2_181703_prj/ZL02_LED2_181703_prj.srcs/sources_1/bd/ZL02_Blk_181703/ip/ZL02_Blk_181703_axi_gpio_0_0/ZL02_Blk_181703_axi_gpio_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'ZL02_Blk_181703_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/s181703/ZL02_LED2_181703_prj/ZL02_LED2_181703_prj.srcs/sources_1/bd/ZL02_Blk_181703/ip/ZL02_Blk_181703_axi_gpio_0_0/ZL02_Blk_181703_axi_gpio_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ZL02_Blk_181703_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/s181703/ZL02_LED2_181703_prj/ZL02_LED2_181703_prj.srcs/sources_1/bd/ZL02_Blk_181703/ip/ZL02_Blk_181703_axi_gpio_0_0/ZL02_Blk_181703_axi_gpio_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'ZL02_Blk_181703_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
