# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/s181703/ZL03_IP1_181703_prj/ZL03_IP1_181703_prj.srcs/sources_1/bd/ZL03_181703/ip/ZL03_181703_rst_ps7_0_50M_0/ZL03_181703_rst_ps7_0_50M_0.xci
# IP: The module: 'ZL03_181703_rst_ps7_0_50M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/s181703/ZL03_IP1_181703_prj/ZL03_IP1_181703_prj.srcs/sources_1/bd/ZL03_181703/ip/ZL03_181703_rst_ps7_0_50M_0/ZL03_181703_rst_ps7_0_50M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'ZL03_181703_rst_ps7_0_50M_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/s181703/ZL03_IP1_181703_prj/ZL03_IP1_181703_prj.srcs/sources_1/bd/ZL03_181703/ip/ZL03_181703_rst_ps7_0_50M_0/ZL03_181703_rst_ps7_0_50M_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'ZL03_181703_rst_ps7_0_50M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/s181703/ZL03_IP1_181703_prj/ZL03_IP1_181703_prj.srcs/sources_1/bd/ZL03_181703/ip/ZL03_181703_rst_ps7_0_50M_0/ZL03_181703_rst_ps7_0_50M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ZL03_181703_rst_ps7_0_50M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: D:/s181703/ZL03_IP1_181703_prj/ZL03_IP1_181703_prj.srcs/sources_1/bd/ZL03_181703/ip/ZL03_181703_rst_ps7_0_50M_0/ZL03_181703_rst_ps7_0_50M_0.xci
# IP: The module: 'ZL03_181703_rst_ps7_0_50M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/s181703/ZL03_IP1_181703_prj/ZL03_IP1_181703_prj.srcs/sources_1/bd/ZL03_181703/ip/ZL03_181703_rst_ps7_0_50M_0/ZL03_181703_rst_ps7_0_50M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'ZL03_181703_rst_ps7_0_50M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/s181703/ZL03_IP1_181703_prj/ZL03_IP1_181703_prj.srcs/sources_1/bd/ZL03_181703/ip/ZL03_181703_rst_ps7_0_50M_0/ZL03_181703_rst_ps7_0_50M_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'ZL03_181703_rst_ps7_0_50M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/s181703/ZL03_IP1_181703_prj/ZL03_IP1_181703_prj.srcs/sources_1/bd/ZL03_181703/ip/ZL03_181703_rst_ps7_0_50M_0/ZL03_181703_rst_ps7_0_50M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ZL03_181703_rst_ps7_0_50M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
