# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/ZL01_Blk_s181703/ZL01_Blk_s181703.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ZL01_Blk_s181703 || ORIG_REF_NAME==ZL01_Blk_s181703} -quiet] -quiet

# IP: bd/ZL01_Blk_s181703/ip/ZL01_Blk_s181703_processing_system7_0_0/ZL01_Blk_s181703_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ZL01_Blk_s181703_processing_system7_0_0 || ORIG_REF_NAME==ZL01_Blk_s181703_processing_system7_0_0} -quiet] -quiet

# IP: bd/ZL01_Blk_s181703/ip/ZL01_Blk_s181703_axi_gpio_0_0/ZL01_Blk_s181703_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ZL01_Blk_s181703_axi_gpio_0_0 || ORIG_REF_NAME==ZL01_Blk_s181703_axi_gpio_0_0} -quiet] -quiet

# IP: bd/ZL01_Blk_s181703/ip/ZL01_Blk_s181703_ps7_0_axi_periph_0/ZL01_Blk_s181703_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ZL01_Blk_s181703_ps7_0_axi_periph_0 || ORIG_REF_NAME==ZL01_Blk_s181703_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/ZL01_Blk_s181703/ip/ZL01_Blk_s181703_rst_ps7_0_50M_0/ZL01_Blk_s181703_rst_ps7_0_50M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ZL01_Blk_s181703_rst_ps7_0_50M_0 || ORIG_REF_NAME==ZL01_Blk_s181703_rst_ps7_0_50M_0} -quiet] -quiet

# IP: bd/ZL01_Blk_s181703/ip/ZL01_Blk_s181703_auto_pc_0/ZL01_Blk_s181703_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ZL01_Blk_s181703_auto_pc_0 || ORIG_REF_NAME==ZL01_Blk_s181703_auto_pc_0} -quiet] -quiet

# XDC: bd/ZL01_Blk_s181703/ZL01_Blk_s181703_ooc.xdc
